Fix build with Boost 1.77 (missing include)
We're relying on boost::geometry so we need to include the "main"
header for it.

Fixes errors like:
error: ‘boost::geometry::strategy::disjoint’ has not been declared

Bug: https://bugs.gentoo.org/808771