Add missing Boost Filesystem fstream header
Fixes error with GCC 12:

src/slic3r/GUI/Plater.cpp:5795:37: error: ‘fstream’ is not a member of ‘fs’; did you mean ‘std::fstream’?
 5795 |                 fs::fstream file(final_path, std::ios::out | std::ios::binary | std::ios::trunc);
      |                     ^~~~~~~